# Generated by Django 4.2.16 on 2024-12-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0007_discount_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='item',
        ),
    ]
