# Generated by Django 4.2.16 on 2024-12-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0003_discount_order_discount_amount_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finalproject.item'),
        ),
    ]
