# Generated by Django 4.2.16 on 2024-12-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0005_discount_category_discount_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='item',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='seller',
        ),
    ]
