# Generated by Django 4.2.16 on 2024-12-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0006_remove_discount_category_remove_discount_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finalproject.item'),
        ),
    ]
